'use strict';

const REGEXP_STRING = '{:([\\w|\\.|:|\\[|\\]]+)\\}';
const BRACKETS_STRING = '\\[:([\\w]+)\\]';

const TEMPLATE_REGEXP_GLOBAL = new RegExp(REGEXP_STRING, 'g');
const TEMPLATE_REGEXP = new RegExp(REGEXP_STRING);
const TEMPLATE_BRACKETS_REGEXP_GLOBAL = new RegExp(BRACKETS_STRING, 'g');
const TEMPLATE_BRACKETS_REGEXP = new RegExp(BRACKETS_STRING);

module.exports.TEMPLATE_REGEXP = TEMPLATE_REGEXP;
module.exports.TEMPLATE_REGEXP_GLOBAL = TEMPLATE_REGEXP_GLOBAL;
module.exports.TEMPLATE_BRACKETS_REGEXP = TEMPLATE_BRACKETS_REGEXP;
module.exports.TEMPLATE_BRACKETS_REGEXP_GLOBAL = TEMPLATE_BRACKETS_REGEXP_GLOBAL;
