version: 2
jobs:
  build:
    docker:
      - image: circleci/node:15-browsers
    working_directory: ~/node
    steps:
      - checkout
      - restore_cache:
          key: v1-dependencies-{{ checksum "package.json"}}
      - run:
          name: Run yarn install
          command: yarn install
      - run:
          name: prepare greenkeeper-lockfile
          command: |
            echo 'export PATH=$(yarn global bin):$PATH' >> $BASH_ENV
            source $BASH_ENV
            yarn global add greenkeeper-lockfile@1
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Run lint
          command: yarn lint
      - run:
          name: tsc
          command: yarn tsc
      - run: greenkeeper-lockfile-upload
